require 'settings'
require 'keymaps'

-- Plugins
require 'plugins.paq'
require 'plugins.impatient'
require 'plugins.lualine'
require 'plugins.bufferline'
require 'plugins.tree'
require 'plugins.telescope'
require 'plugins.treesitter'
require 'plugins.gitsigns'
require 'plugins.dashboard'
require 'plugins.lsp-config'
require 'plugins.cmp'
require 'plugins.autopairs'
